#!/usr/bin/env python3
"""
index-kb.py — wiki/ 디렉토리를 스캔하여 INDEX.md, TAGS.md, GRAPH.md를 자동 생성.

Usage:
    python3 index-kb.py ~/Obsidian/buzzvil-wiki
    python3 index-kb.py ~/Obsidian/ai-wiki
    python3 index-kb.py  # 모든 ~/Obsidian/*-wiki/ vault 일괄 처리
"""

import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

def parse_frontmatter(content: str) -> dict:
    """YAML frontmatter를 간이 파싱한다. 외부 의존성 없음."""
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if not match:
        return {}

    result = {}
    for line in match.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()

        # [a, b, c] 형식의 리스트 파싱
        if value.startswith("[") and value.endswith("]"):
            items = value[1:-1]
            result[key] = [
                item.strip().strip("'\"")
                for item in items.split(",")
                if item.strip()
            ]
        # 따옴표 제거
        elif value.startswith(("'", '"')) and value.endswith(("'", '"')):
            result[key] = value[1:-1]
        else:
            result[key] = value

    return result


def extract_wikilinks(content: str) -> list[str]:
    """[[wikilink]] 패턴을 추출한다."""
    return re.findall(r"\[\[([^\]]+)\]\]", content)


def scan_wiki(vault_path: Path) -> list[dict]:
    """wiki/ 디렉토리의 모든 .md 파일을 스캔하여 메타데이터를 수집한다."""
    wiki_dir = vault_path / "wiki"
    if not wiki_dir.exists():
        return []

    docs = []
    skip_files = {"INDEX.md", "TAGS.md", "GRAPH.md"}

    for md_file in sorted(wiki_dir.rglob("*.md")):
        if md_file.name in skip_files:
            continue

        rel_path = md_file.relative_to(wiki_dir)
        # 최상위 디렉토리를 카테고리로 사용
        parts = rel_path.parts
        if len(parts) < 2:
            continue  # 카테고리 없는 최상위 파일은 건너뜀

        category = parts[0]
        content = md_file.read_text(encoding="utf-8")
        fm = parse_frontmatter(content)
        wikilinks = extract_wikilinks(content)

        # 제목: frontmatter title 또는 첫 번째 # 헤딩
        title = fm.get("title", "")
        if not title:
            title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
            title = title_match.group(1).strip() if title_match else md_file.stem

        docs.append({
            "title": title,
            "category": category,
            "rel_path": str(rel_path),
            "tags": fm.get("tags", []) or [],
            "keywords": fm.get("keywords", ""),
            "sources": fm.get("sources", []) or [],
            "created": str(fm.get("created", "")),
            "updated": str(fm.get("updated", date.today().isoformat())),
            "wikilinks": wikilinks,
        })

    return docs


def generate_index(docs: list[dict]) -> str:
    """INDEX.md를 생성한다."""
    by_category = defaultdict(list)
    for doc in docs:
        by_category[doc["category"]].append(doc)

    total = len(docs)
    num_categories = len(by_category)

    lines = [
        "<!-- AUTO-GENERATED by index-kb.py — do not edit manually -->",
        "<!-- Search tip: rg \"keyword\" wiki/INDEX.md to find relevant docs -->",
        f"# Knowledge Base Index",
        "",
        f"> **{total} documents** across **{num_categories} categories**",
        "",
        "## By Category",
        "",
    ]

    for category in sorted(by_category.keys()):
        cat_docs = sorted(by_category[category], key=lambda d: d["title"])
        lines.append(f"### {category}")
        lines.append("")
        lines.append("| Document | Description | Keywords | Updated |")
        lines.append("|----------|-------------|----------|---------|")
        for doc in cat_docs:
            title = doc["title"]
            path = doc["rel_path"]
            keywords = doc["keywords"] if isinstance(doc["keywords"], str) else ", ".join(doc["keywords"])
            updated = doc["updated"]
            # description: 첫 번째 태그 기반 또는 빈칸
            desc = ", ".join(doc["tags"][:3]) if doc["tags"] else ""
            lines.append(f"| [{title}]({path}) | {desc} | {keywords} | {updated} |")
        lines.append("")

    return "\n".join(lines)


def generate_tags(docs: list[dict]) -> str:
    """TAGS.md를 생성한다."""
    tag_docs = defaultdict(list)
    for doc in docs:
        for tag in doc["tags"]:
            tag_docs[tag].append(doc)

    total_tags = len(tag_docs)
    total_docs = len(docs)

    lines = [
        "<!-- AUTO-GENERATED by index-kb.py — do not edit manually -->",
        "# Tag Index",
        "",
        f"> **{total_tags} unique tags** across **{total_docs} documents**",
        "",
        "## Tag Cloud",
        "",
    ]

    # 빈도순 정렬
    sorted_tags = sorted(tag_docs.items(), key=lambda x: (-len(x[1]), x[0]))
    cloud = " · ".join(f"{tag} ({len(tag_docs)})" for tag, tag_docs in sorted_tags)
    lines.append(cloud)
    lines.append("")

    # Documents by Tag
    lines.append("## Documents by Tag")
    lines.append("")
    for tag, tag_doc_list in sorted_tags:
        lines.append(f"### {tag}")
        lines.append("")
        for doc in sorted(tag_doc_list, key=lambda d: d["title"]):
            lines.append(f"- [{doc['title']}]({doc['rel_path']})")
        lines.append("")

    return "\n".join(lines)


def generate_graph(docs: list[dict]) -> str:
    """GRAPH.md를 생성한다."""
    lines = [
        "<!-- AUTO-GENERATED by index-kb.py — do not edit manually -->",
        "# Cross-Reference Graph",
        "",
        "## Link Map",
        "",
        "| Source | Links To |",
        "|--------|----------|",
    ]

    # 제목 → 문서 매핑 (wikilink 해소용)
    title_to_doc = {}
    for doc in docs:
        title_to_doc[doc["title"]] = doc

    for doc in sorted(docs, key=lambda d: d["title"]):
        if not doc["wikilinks"]:
            continue
        # wikilink를 실제 문서 링크로 변환
        link_strs = []
        for wl in doc["wikilinks"]:
            if wl in title_to_doc:
                target = title_to_doc[wl]
                link_strs.append(f"[{wl}]({target['rel_path']})")
            else:
                link_strs.append(wl)

        if len(link_strs) > 5:
            visible = ", ".join(link_strs[:5])
            links_str = f"{visible} +{len(link_strs) - 5} more"
        else:
            links_str = ", ".join(link_strs)

        lines.append(f"| [{doc['title']}]({doc['rel_path']}) | {links_str} |")

    if len(lines) == 7:  # 헤더만 있고 데이터 없음
        lines.append("| _문서 없음_ | |")

    return "\n".join(lines)


def process_vault(vault_path: Path) -> None:
    """단일 vault를 처리한다."""
    wiki_dir = vault_path / "wiki"
    if not wiki_dir.exists():
        print(f"  [SKIP] {vault_path.name}: wiki/ 디렉토리 없음")
        return

    docs = scan_wiki(vault_path)
    print(f"  {vault_path.name}: {len(docs)} documents found")

    # INDEX.md 생성
    index_content = generate_index(docs)
    (wiki_dir / "INDEX.md").write_text(index_content, encoding="utf-8")
    print(f"    INDEX.md updated")

    # TAGS.md 생성
    tags_content = generate_tags(docs)
    (wiki_dir / "TAGS.md").write_text(tags_content, encoding="utf-8")
    print(f"    TAGS.md updated")

    # GRAPH.md 생성
    graph_content = generate_graph(docs)
    (wiki_dir / "GRAPH.md").write_text(graph_content, encoding="utf-8")
    print(f"    GRAPH.md updated")


def main():
    if len(sys.argv) > 1:
        # 특정 vault 경로 지정
        vault_path = Path(sys.argv[1]).expanduser()
        if not vault_path.exists():
            print(f"Error: {vault_path} does not exist")
            sys.exit(1)
        print(f"[index-kb] Processing {vault_path.name}")
        process_vault(vault_path)
    else:
        # 모든 *-wiki vault 일괄 처리
        obsidian_dir = Path.home() / "Obsidian"
        vaults = sorted(obsidian_dir.glob("*-wiki"))
        if not vaults:
            print("No *-wiki vaults found in ~/Obsidian/")
            sys.exit(1)

        print(f"[index-kb] Found {len(vaults)} vaults")
        for vault_path in vaults:
            process_vault(vault_path)

    print("[index-kb] Done")


if __name__ == "__main__":
    main()
